name: Build APK

on:
  push:
    branches:
      - master
      - main
  workflow_dispatch:

env:
  BUILD_NUMBER: 1
  BUILD_VERSION: 1.0.0
  PYTHON_VERSION: 3.12.2
  FLUTTER_VERSION: 3.22.2

jobs:
  build-apk:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Verify files exist
      run: |
        echo "Files in repository:"
        ls -la
        echo ""
        echo "Checking for main.py:"
        if [ -f "main.py" ]; then
          echo "✓ main.py found!"
        else
          echo "✗ ERROR: main.py not found!"
          exit 1
        fi
        echo ""
        echo "Checking for requirements.txt:"
        if [ -f "requirements.txt" ]; then
          echo "✓ requirements.txt found!"
          cat requirements.txt
        else
          echo "✗ WARNING: requirements.txt not found!"
        fi

    - name: Setup Python ${{ env.PYTHON_VERSION }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        # Install flet first
        pip install flet
        # Install other requirements if the file exists
        if [ -f "requirements.txt" ]; then
          pip install -r requirements.txt
        fi

    - name: Setup Flutter ${{ env.FLUTTER_VERSION }}
      uses: subosito/flutter-action@v2
      with:
        flutter-version: ${{ env.FLUTTER_VERSION }}

    - name: Setup Java JDK
      uses: actions/setup-java@v4.2.1
      with:
        distribution: 'temurin'
        java-version: '21'

    - name: Build APK
      run: |
        flutter config --no-analytics
        flutter doctor
        flet build apk --verbose --build-number=$BUILD_NUMBER --build-version=$BUILD_VERSION

    - name: Upload APK Artifact
      uses: actions/upload-artifact@v4.3.4
      with:
        name: app-apk
        path: build/apk
        if-no-files-found: error
        overwrite: true
